In [1]:
print(123)

123

In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'3.0.5'

In [4]:
df = pd.read_csv('data/car_fuel_efficiency_2026.csv')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

In [6]:
df.shape

(10000, 11)

In [7]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [8]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

In [9]:
df.describe().round(2)

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.00,10000.00,10000.00,10000.00,9123.00,10000.00,9736.00,10000.00
mean,1999.55,3.50,2268.81,6.04,254.45,4286.75,18.89,30.00
std,14.21,0.95,183.45,0.54,22.84,266.21,1.28,2.93
min,1975.00,2.00,1590.00,4.00,171.00,3320.00,14.00,19.80
25%,1987.00,3.00,2150.00,6.00,239.00,4110.00,18.00,28.00
50%,2000.00,4.00,2270.00,6.00,254.00,4280.00,18.90,30.00
75%,2012.00,4.00,2390.00,6.00,270.00,4470.00,19.70,31.90
max,2024.00,5.00,3110.00,8.00,334.00,5460.00,23.80,41.20

In [10]:
df['horsepower'].median()

np.float64(254.0)

In [11]:
df['horsepower'].value_counts()

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
        ...
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [12]:
df['horsepower'] = df['horsepower'].fillna(252)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           10000 non-null  float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB

In [14]:
df['horsepower'].median()

np.float64(252.0)

Q7

In [15]:
df['origin'].value_counts()

origin
USA       4202
Asia      2994
Europe    2804
Name: count, dtype: int64

In [16]:
df_asia = df[df['origin'] == 'Asia']
df_asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [25]:
df_asia = df_asia[['vehicle_weight', 'model_year']].head(7 )
df_asia.head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [26]:
X = df_asia[["vehicle_weight", "model_year"]].to_numpy(dtype=float)
X.shape

(7, 2)

In [27]:
XTX = X.T @ X
XTX

array([[1.3195050e+08, 6.0750580e+07],
       [6.0750580e+07, 2.8041424e+07]])

In [28]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [29]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200], dtype=float)
y

array([1100., 1300.,  800.,  900., 1000., 1100., 1200.])

In [30]:
print("y shape:", y.shape)  # Should be (7,)

y shape: (7,)

In [31]:
print(X.shape)
print(X.T.shape)
print(y.shape)

(7, 2)
(2, 7)
(7,)

In [32]:
w = XTX_inv @ X.T @ y
print(w)

[0.13644777 0.2327492 ]

In [35]:
w.sum().round(3)

np.float64(0.369)